development:
  adapter: postgresql
  database: scrum_development
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: mypass

test:
  adapter: postgresql
  database: scrum_test
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  password: mypass

production:
  adapter: postgresql
  database: scrum_production
  pool: 5
  timeout: 5000
